"""ифслкщдд

Revision ID: 0d9ffdecac5e
Revises: a8dbda741f7b
Create Date: 2023-12-03 17:34:42.761139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d9ffdecac5e'
down_revision: Union[str, None] = 'a8dbda741f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'tags')
    op.drop_column('chats', 'resource')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('resource', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chats', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
