"""datetime

Revision ID: 3bb45e69817b
Revises: ba62eddd2967
Create Date: 2023-12-03 02:47:50.413109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb45e69817b'
down_revision: Union[str, None] = 'ba62eddd2967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="date::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="date::text")
    # ### end Alembic commands ###
