"""update_model

Revision ID: 4cc70bf98b6c
Revises: 3bb45e69817b
Create Date: 2023-12-03 17:25:26.903755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc70bf98b6c'
down_revision: Union[str, None] = '3bb45e69817b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('resource', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('chats', 'id_post',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chats', 'id_channel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chats', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chats', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chats', 'id_channel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chats', 'id_post',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('chats', 'tags')
    op.drop_column('chats', 'resource')
    # ### end Alembic commands ###
